#!/usr/bin/with-contenv bash

# Clone Monitorr & Logarr repos
[[ ! -d /config/www/monitorr/.git ]] && \
git clone https://github.com/Monitorr/monitorr.git /config/www/monitorr && \
[[ ! -d /config/www/monitorr/logarr/.git ]] && \
git clone https://github.com/Monitorr/logarr.git /config/www/monitorr/logarr

# Set permissions
chown -R abc:abc \
	/config
