#!/usr/bin/with-contenv bash

# Clone Monitorr & Logarr repos
[[ ! -d /config/www/Dashboard/.git ]] && \
git clone https://github.com/Monitorr/monitorr.git /config/www/monitorr
git clone https://github.com/Monitorr/logarr.git /config/www/monitorr/logarr

# Set permissions
chown -R abc:abc \
	/config
